Parameters:
   NameOfService:
     Description: "The name of the service this stack is used for"
     Type: String  
   KeyName:
      Description: Name of keypair to enable ssh access to an EC2 instance
      Type: AWS::EC2::KeyPair::KeyName
   InstTypeParam:
      Description: WHich Type of instance you gonna select 
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - m1.small
        - m1.large
Mappings:
  bharathRegionMap:
    us-east-1:
      AMI: ami-1853ac65
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721
Resources:
  BKREc2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstTypeParam
      ImageId: 
        Fn::FindInMap:
          - bharathRegionMap
          - !Ref AWS::Region
          - AMI
      UserData:
        !Base64 |
                  #!/bin/bash
                  yum update -y
                  yum install httpd -y
                  service httpd start
      Tags:
       - Key: Name   
         Value: !Join 
          - "_"
          - - "Ec2"
            - "Instance"
            - "launched"
            - " by"
            - "bharath"
            - "In the AWS Region Called"
            - !Ref AWS::Region
       - Key: BharathName
         Value: !Ref NameOfService
                 
      KeyName: !Ref KeyName
      SecurityGroups: 
       - !Ref BKRSecurityGROUP
  BKRSecurityGROUP:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceDNSName:
    Value: !GetAtt 
      - BKREc2Instance
      - PublicDnsName
