Resources: 
  BKRSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
     GroupDescription: Enable SSH port 22
     SecurityGroupIngress:
     - IpProtocol: tcp 
       FromPort: 22
       ToPort: 22
       CidrIp: 0.0.0.0/0